### ISSUE TITLE
Oracle JDBC driver need to be updated

### ISSUE THREAD

**Issue by mirasrael** [thehyve/transmart-data#31]
In lib/makefile.inc JDBC_DRIVER_ORA is set to ojdbc6-12.1.0.1.0.jar, but this version of driver has known issue (https://community.oracle.com/thread/2558937) which fixed in  ojdbc6-12.1.0.2.0.jar. You can meet this issue while trying to upload MIRNA dictionary with command:
```
make -C data/oracle/ load_mirna_dictionary 
```
you will get error:
```
70910 [main] INFO  org.transmartproject.pipeline.dictionary.DictionaryLoader  - Insert 391569669:hsa-let-7a-2:SYNONYM:BIO_MARKER.MIRNA:Alias into BIO_DATA_EXT_CODE ...
Exception in thread "main" java.lang.NullPointerException                                                                                                              
        at oracle.jdbc.driver.AutoKeyInfo.initMetaDataKeyFlag(AutoKeyInfo.java:404)                                                                                    
        at oracle.jdbc.driver.AutoKeyInfo.initMetaData(AutoKeyInfo.java:392)                                                                                           
        at oracle.jdbc.driver.OracleReturnResultSet.getMetaData(OracleReturnResultSet.java:77)                                                                         
        at groovy.sql.Sql.calculateKeys(Sql.java:3789)                                                                                                                 
        at groovy.sql.Sql.executeInsert(Sql.java:2418)                                                                                                                 
        at groovy.sql.Sql.executeInsert(Sql.java:2458)                                                                                                                 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)                                                                               
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                       
```

**Comment by cataphract** [comment]
Fixed in b54f50ada6d1167c225cac9946fb16c893ed889e.
